# Generated by Django 3.0.1 on 2020-03-30 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_songs_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='songs',
            name='cover',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
