# Generated by Django 3.0.1 on 2020-03-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200330_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='user',
        ),
    ]
