version: '3'

services:
  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/my_app_dir
    ports:
      - "5000:8000"
    depends_on:
      - mydb
  mydb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3308:3306'
    environment:
       MYSQL_DATABASE: 'trying'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: '159753'
       MYSQL_ROOT_PASSWORD: '159753'
  